name: "Get Clubhouse Story Info"
description: "Get information from the clubhouse story"
inputs:
  storyId: # id of the story in clubhouse
    description: "Unique identifier for clubhouse story"
    required: true
    default: ""
  token: # token for clubhouse api access
    description: "Clubhouse token"
    required: true
    default: ""
outputs:
  url: # url that redirects to the clubhouse ticket
    description: "Url of the clubhouse story associated with the storyId"
  title: # url that redirects to the clubhouse ticket
    description: "Story Title of the clubhouse story associated with the storyId"
  description: # description that redirects to the clubhouse ticket
    description: "Description of the clubhouse story associated with the storyId"
runs:
  using: "node12"
  main: "dist/index.js"
